import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Starting database seed...');

  // Create trainers
  const trainers = await Promise.all([
    prisma.trainer.upsert({
      where: { id: 'trainer-1' },
      update: {},
      create: {
        id: 'trainer-1',
        name: '김민준',
        title: '피트니스 마스터 트레이너',
        bio: '10년 경력의 피트니스 전문가. 수백 명의 회원들이 목표를 달성하도록 도왔습니다.',
        avatarUrl: '/trainers/trainer-1.jpg',
        specialties: ['strength', 'hiit', 'cardio'],
        certifications: ['NSCA-CPT', 'ACE Certified', 'CrossFit L2'],
        totalWorkouts: 45,
        followerCount: 12500,
        avgRating: 4.9,
      },
    }),
    prisma.trainer.upsert({
      where: { id: 'trainer-2' },
      update: {},
      create: {
        id: 'trainer-2',
        name: '이서연',
        title: '요가 & 필라테스 인스트럭터',
        bio: '마음과 몸의 균형을 찾는 여정을 함께합니다. 인도에서 200시간 요가 TTC 수료.',
        avatarUrl: '/trainers/trainer-2.jpg',
        specialties: ['yoga', 'pilates', 'stretching', 'meditation'],
        certifications: ['RYT-200', 'Pilates Mat Certification', 'Mindfulness Coach'],
        totalWorkouts: 38,
        followerCount: 9800,
        avgRating: 4.8,
      },
    }),
    prisma.trainer.upsert({
      where: { id: 'trainer-3' },
      update: {},
      create: {
        id: 'trainer-3',
        name: '박지훈',
        title: '댄스 피트니스 전문가',
        bio: '춤추며 운동하세요! K-POP 커버댄스부터 줌바까지, 즐거운 운동을 선사합니다.',
        avatarUrl: '/trainers/trainer-3.jpg',
        specialties: ['dance', 'cardio', 'hiit'],
        certifications: ['Zumba Instructor', 'Dance Fitness Certified'],
        totalWorkouts: 32,
        followerCount: 15200,
        avgRating: 4.9,
      },
    }),
  ]);

  console.log(`✅ Created ${trainers.length} trainers`);

  // Create workouts
  const workouts = await Promise.all([
    // Strength workouts
    prisma.workout.upsert({
      where: { id: 'workout-strength-1' },
      update: {},
      create: {
        id: 'workout-strength-1',
        title: '전신 근력 운동 30분',
        subtitle: '덤벨로 완성하는 탄탄한 바디',
        description: '상체와 하체를 골고루 단련하는 전신 근력 운동입니다. 덤벨만 있으면 집에서도 체육관 못지않은 운동이 가능합니다.',
        thumbnailUrl: '/workouts/strength-1.jpg',
        previewVideoUrl: '/workouts/strength-1-preview.mp4',
        category: 'strength',
        bodyParts: ['full_body', 'arms', 'legs', 'core'],
        equipment: ['dumbbell', 'mat'],
        difficulty: 'intermediate',
        duration: 30,
        calories: 280,
        trainerId: 'trainer-1',
        accessType: 'free',
        xpReward: 75,
        tags: ['근력', '전신', '덤벨', '홈트'],
      },
    }),
    prisma.workout.upsert({
      where: { id: 'workout-strength-2' },
      update: {},
      create: {
        id: 'workout-strength-2',
        title: '상체 집중 근력 운동',
        subtitle: '탄탄한 팔과 어깨 만들기',
        description: '팔, 어깨, 가슴, 등을 집중적으로 단련합니다. 매끈한 라인과 강한 상체를 원한다면 이 운동을 추천합니다.',
        thumbnailUrl: '/workouts/strength-2.jpg',
        category: 'strength',
        bodyParts: ['upper_body', 'arms', 'shoulders', 'chest', 'back'],
        equipment: ['dumbbell', 'mat'],
        difficulty: 'intermediate',
        duration: 25,
        calories: 220,
        trainerId: 'trainer-1',
        accessType: 'premium',
        xpReward: 70,
        tags: ['상체', '팔', '어깨', '덤벨'],
      },
    }),
    prisma.workout.upsert({
      where: { id: 'workout-strength-3' },
      update: {},
      create: {
        id: 'workout-strength-3',
        title: '하체 & 힙업 운동',
        subtitle: '탄력있는 하체 라인',
        description: '허벅지, 엉덩이, 종아리를 집중 단련합니다. 탄력있는 하체 라인을 만들어보세요.',
        thumbnailUrl: '/workouts/strength-3.jpg',
        category: 'strength',
        bodyParts: ['lower_body', 'legs', 'glutes'],
        equipment: ['mat', 'resistance_band'],
        difficulty: 'beginner',
        duration: 20,
        calories: 180,
        trainerId: 'trainer-1',
        accessType: 'free',
        xpReward: 50,
        tags: ['하체', '힙업', '엉덩이', '레그'],
      },
    }),

    // HIIT workouts
    prisma.workout.upsert({
      where: { id: 'workout-hiit-1' },
      update: {},
      create: {
        id: 'workout-hiit-1',
        title: '전신 HIIT 20분',
        subtitle: '최대 칼로리 소모',
        description: '20분 동안 전신을 불태우는 고강도 인터벌 트레이닝입니다. 짧은 시간에 최대 효과를 원한다면 이 운동!',
        thumbnailUrl: '/workouts/hiit-1.jpg',
        previewVideoUrl: '/workouts/hiit-1-preview.mp4',
        category: 'hiit',
        bodyParts: ['full_body'],
        equipment: ['none'],
        difficulty: 'advanced',
        duration: 20,
        calories: 300,
        trainerId: 'trainer-1',
        accessType: 'free',
        xpReward: 100,
        tags: ['HIIT', '고강도', '칼로리', '전신'],
      },
    }),
    prisma.workout.upsert({
      where: { id: 'workout-hiit-2' },
      update: {},
      create: {
        id: 'workout-hiit-2',
        title: '초보자 HIIT 15분',
        subtitle: '처음 시작하는 고강도 운동',
        description: 'HIIT가 처음이신가요? 강도를 조절한 입문자용 고강도 인터벌 트레이닝으로 시작해보세요.',
        thumbnailUrl: '/workouts/hiit-2.jpg',
        category: 'hiit',
        bodyParts: ['full_body'],
        equipment: ['none'],
        difficulty: 'beginner',
        duration: 15,
        calories: 180,
        trainerId: 'trainer-1',
        accessType: 'free',
        xpReward: 50,
        tags: ['HIIT', '초보자', '입문'],
      },
    }),

    // Yoga workouts
    prisma.workout.upsert({
      where: { id: 'workout-yoga-1' },
      update: {},
      create: {
        id: 'workout-yoga-1',
        title: '모닝 요가 20분',
        subtitle: '상쾌한 하루의 시작',
        description: '아침에 하는 부드러운 요가로 하루를 시작하세요. 몸을 깨우고 정신을 맑게 해줍니다.',
        thumbnailUrl: '/workouts/yoga-1.jpg',
        previewVideoUrl: '/workouts/yoga-1-preview.mp4',
        category: 'yoga',
        bodyParts: ['full_body'],
        equipment: ['mat'],
        difficulty: 'beginner',
        duration: 20,
        calories: 80,
        trainerId: 'trainer-2',
        accessType: 'free',
        xpReward: 50,
        tags: ['요가', '아침', '스트레칭', '명상'],
      },
    }),
    prisma.workout.upsert({
      where: { id: 'workout-yoga-2' },
      update: {},
      create: {
        id: 'workout-yoga-2',
        title: '빈야사 플로우 요가',
        subtitle: '호흡과 함께하는 움직임',
        description: '호흡에 맞춰 자연스럽게 흐르는 빈야사 요가입니다. 유연성과 근력을 동시에 기를 수 있습니다.',
        thumbnailUrl: '/workouts/yoga-2.jpg',
        category: 'yoga',
        bodyParts: ['full_body', 'core'],
        equipment: ['mat', 'yoga_block'],
        difficulty: 'intermediate',
        duration: 45,
        calories: 200,
        trainerId: 'trainer-2',
        accessType: 'premium',
        xpReward: 90,
        tags: ['요가', '빈야사', '플로우'],
      },
    }),

    // Pilates workouts
    prisma.workout.upsert({
      where: { id: 'workout-pilates-1' },
      update: {},
      create: {
        id: 'workout-pilates-1',
        title: '코어 필라테스 25분',
        subtitle: '탄탄한 복부 만들기',
        description: '코어 근육을 집중적으로 강화하는 필라테스 프로그램입니다. 자세 교정과 복부 강화에 효과적입니다.',
        thumbnailUrl: '/workouts/pilates-1.jpg',
        category: 'pilates',
        bodyParts: ['core', 'back'],
        equipment: ['mat'],
        difficulty: 'intermediate',
        duration: 25,
        calories: 150,
        trainerId: 'trainer-2',
        accessType: 'free',
        xpReward: 65,
        tags: ['필라테스', '코어', '복부', '자세교정'],
      },
    }),

    // Dance workouts
    prisma.workout.upsert({
      where: { id: 'workout-dance-1' },
      update: {},
      create: {
        id: 'workout-dance-1',
        title: 'K-POP 댄스 워크아웃',
        subtitle: '신나는 K-POP과 함께',
        description: '인기 K-POP 음악에 맞춰 춤추며 운동하세요! 재미있게 칼로리를 태울 수 있습니다.',
        thumbnailUrl: '/workouts/dance-1.jpg',
        previewVideoUrl: '/workouts/dance-1-preview.mp4',
        category: 'dance',
        bodyParts: ['full_body'],
        equipment: ['none'],
        difficulty: 'beginner',
        duration: 30,
        calories: 250,
        trainerId: 'trainer-3',
        accessType: 'free',
        xpReward: 75,
        tags: ['댄스', 'K-POP', '유산소', '재미'],
      },
    }),
    prisma.workout.upsert({
      where: { id: 'workout-dance-2' },
      update: {},
      create: {
        id: 'workout-dance-2',
        title: '줌바 피트니스',
        subtitle: '라틴 리듬의 열정',
        description: '라틴 음악에 맞춰 춤추는 줌바 피트니스! 전신 유산소 운동으로 스트레스 해소까지.',
        thumbnailUrl: '/workouts/dance-2.jpg',
        category: 'dance',
        bodyParts: ['full_body'],
        equipment: ['none'],
        difficulty: 'intermediate',
        duration: 45,
        calories: 400,
        trainerId: 'trainer-3',
        accessType: 'premium',
        xpReward: 100,
        tags: ['줌바', '댄스', '라틴', '유산소'],
      },
    }),

    // Stretching
    prisma.workout.upsert({
      where: { id: 'workout-stretching-1' },
      update: {},
      create: {
        id: 'workout-stretching-1',
        title: '취침 전 스트레칭',
        subtitle: '편안한 밤을 위한 이완',
        description: '하루의 피로를 풀어주는 부드러운 스트레칭입니다. 숙면에 도움이 됩니다.',
        thumbnailUrl: '/workouts/stretching-1.jpg',
        category: 'stretching',
        bodyParts: ['full_body'],
        equipment: ['mat'],
        difficulty: 'beginner',
        duration: 15,
        calories: 40,
        trainerId: 'trainer-2',
        accessType: 'free',
        xpReward: 40,
        tags: ['스트레칭', '취침', '이완', '수면'],
      },
    }),

    // Cardio
    prisma.workout.upsert({
      where: { id: 'workout-cardio-1' },
      update: {},
      create: {
        id: 'workout-cardio-1',
        title: '유산소 킥복싱',
        subtitle: '펀치와 킥으로 스트레스 해소',
        description: '킥복싱 동작으로 구성된 유산소 운동입니다. 스트레스 해소와 체력 향상에 효과적입니다.',
        thumbnailUrl: '/workouts/cardio-1.jpg',
        category: 'cardio',
        bodyParts: ['full_body', 'arms', 'legs'],
        equipment: ['none'],
        difficulty: 'intermediate',
        duration: 30,
        calories: 320,
        trainerId: 'trainer-1',
        accessType: 'premium',
        xpReward: 80,
        tags: ['유산소', '킥복싱', '스트레스해소'],
      },
    }),
  ]);

  console.log(`✅ Created ${workouts.length} workouts`);

  // Create exercises for the first HIIT workout
  const exercises = await Promise.all([
    prisma.exercise.upsert({
      where: { id: 'exercise-1' },
      update: {},
      create: {
        id: 'exercise-1',
        workoutId: 'workout-hiit-1',
        sortOrder: 1,
        name: '점핑잭',
        description: '전신 워밍업 동작으로 심박수를 높입니다.',
        videoUrl: '/exercises/jumping-jack.mp4',
        thumbnailUrl: '/exercises/jumping-jack.jpg',
        type: 'timed',
        duration: 45,
        sets: 1,
        primaryMuscle: 'full_body',
        instructions: [
          '발을 모으고 팔은 옆에 둡니다',
          '점프하면서 다리를 벌리고 팔을 머리 위로 올립니다',
          '다시 점프하며 시작 자세로 돌아옵니다',
          '리듬에 맞춰 반복합니다',
        ],
        tips: ['착지할 때 무릎을 살짝 구부립니다', '코어에 힘을 유지합니다'],
        commonMistakes: ['착지 시 무릎을 너무 펴는 것', '팔 동작을 생략하는 것'],
        caloriesPerMinute: 10,
      },
    }),
    prisma.exercise.upsert({
      where: { id: 'exercise-2' },
      update: {},
      create: {
        id: 'exercise-2',
        workoutId: 'workout-hiit-1',
        sortOrder: 2,
        name: '휴식',
        description: '다음 동작을 위한 짧은 휴식입니다.',
        videoUrl: '/exercises/rest.mp4',
        thumbnailUrl: '/exercises/rest.jpg',
        type: 'rest',
        duration: 15,
        sets: 1,
        primaryMuscle: 'full_body',
        instructions: ['호흡을 가다듬습니다', '물을 마셔도 좋습니다'],
        tips: [],
        commonMistakes: [],
        caloriesPerMinute: 1,
      },
    }),
    prisma.exercise.upsert({
      where: { id: 'exercise-3' },
      update: {},
      create: {
        id: 'exercise-3',
        workoutId: 'workout-hiit-1',
        sortOrder: 3,
        name: '스쿼트',
        description: '하체 근력과 폭발력을 기르는 기본 동작입니다.',
        videoUrl: '/exercises/squat.mp4',
        thumbnailUrl: '/exercises/squat.jpg',
        type: 'timed',
        duration: 45,
        sets: 1,
        primaryMuscle: 'legs',
        secondaryMuscles: ['glutes', 'core'],
        instructions: [
          '발을 어깨 너비로 벌립니다',
          '엉덩이를 뒤로 빼며 앉습니다',
          '허벅지가 바닥과 평행이 될 때까지 내려갑니다',
          '발 뒤꿈치로 밀며 일어납니다',
        ],
        tips: ['무릎이 발끝을 넘지 않도록 합니다', '허리를 곧게 유지합니다'],
        commonMistakes: ['무릎이 안쪽으로 꺾이는 것', '상체가 앞으로 숙여지는 것'],
        modifications: {
          easier: '의자에 살짝 앉았다 일어나기',
          harder: '점프 스쿼트',
        },
        caloriesPerMinute: 8,
      },
    }),
    prisma.exercise.upsert({
      where: { id: 'exercise-4' },
      update: {},
      create: {
        id: 'exercise-4',
        workoutId: 'workout-hiit-1',
        sortOrder: 4,
        name: '휴식',
        description: '다음 동작을 위한 짧은 휴식입니다.',
        videoUrl: '/exercises/rest.mp4',
        thumbnailUrl: '/exercises/rest.jpg',
        type: 'rest',
        duration: 15,
        sets: 1,
        primaryMuscle: 'full_body',
        instructions: ['호흡을 가다듬습니다'],
        tips: [],
        commonMistakes: [],
        caloriesPerMinute: 1,
      },
    }),
    prisma.exercise.upsert({
      where: { id: 'exercise-5' },
      update: {},
      create: {
        id: 'exercise-5',
        workoutId: 'workout-hiit-1',
        sortOrder: 5,
        name: '푸시업',
        description: '상체 근력을 기르는 기본 동작입니다.',
        videoUrl: '/exercises/pushup.mp4',
        thumbnailUrl: '/exercises/pushup.jpg',
        type: 'timed',
        duration: 45,
        sets: 1,
        primaryMuscle: 'chest',
        secondaryMuscles: ['arms', 'shoulders', 'core'],
        instructions: [
          '플랭크 자세에서 시작합니다',
          '팔꿈치를 구부리며 가슴을 바닥으로 내립니다',
          '팔을 펴며 시작 자세로 돌아옵니다',
        ],
        tips: ['몸을 일직선으로 유지합니다', '팔꿈치는 45도 각도로 유지합니다'],
        commonMistakes: ['엉덩이가 처지거나 올라가는 것', '목을 앞으로 빼는 것'],
        modifications: {
          easier: '무릎 대고 푸시업',
          harder: '다이아몬드 푸시업',
        },
        caloriesPerMinute: 9,
      },
    }),
    prisma.exercise.upsert({
      where: { id: 'exercise-6' },
      update: {},
      create: {
        id: 'exercise-6',
        workoutId: 'workout-hiit-1',
        sortOrder: 6,
        name: '휴식',
        description: '다음 동작을 위한 짧은 휴식입니다.',
        videoUrl: '/exercises/rest.mp4',
        thumbnailUrl: '/exercises/rest.jpg',
        type: 'rest',
        duration: 15,
        sets: 1,
        primaryMuscle: 'full_body',
        instructions: ['호흡을 가다듬습니다'],
        tips: [],
        commonMistakes: [],
        caloriesPerMinute: 1,
      },
    }),
    prisma.exercise.upsert({
      where: { id: 'exercise-7' },
      update: {},
      create: {
        id: 'exercise-7',
        workoutId: 'workout-hiit-1',
        sortOrder: 7,
        name: '버피',
        description: '전신을 사용하는 고강도 동작입니다.',
        videoUrl: '/exercises/burpee.mp4',
        thumbnailUrl: '/exercises/burpee.jpg',
        type: 'timed',
        duration: 45,
        sets: 1,
        primaryMuscle: 'full_body',
        secondaryMuscles: ['chest', 'legs', 'core'],
        instructions: [
          '서있는 자세에서 시작합니다',
          '스쿼트 자세로 내려가며 손을 바닥에 짚습니다',
          '점프하며 다리를 뒤로 뻗어 플랭크 자세를 만듭니다',
          '푸시업을 합니다',
          '다리를 앞으로 당기고 점프하며 일어납니다',
        ],
        tips: ['동작을 연결하여 부드럽게 수행합니다', '착지 시 충격을 흡수합니다'],
        commonMistakes: ['푸시업을 생략하는 것', '점프 없이 일어서는 것'],
        modifications: {
          easier: '푸시업과 점프 생략',
          harder: '턱업 버피',
        },
        caloriesPerMinute: 15,
      },
    }),
    prisma.exercise.upsert({
      where: { id: 'exercise-8' },
      update: {},
      create: {
        id: 'exercise-8',
        workoutId: 'workout-hiit-1',
        sortOrder: 8,
        name: '휴식',
        description: '다음 동작을 위한 짧은 휴식입니다.',
        videoUrl: '/exercises/rest.mp4',
        thumbnailUrl: '/exercises/rest.jpg',
        type: 'rest',
        duration: 15,
        sets: 1,
        primaryMuscle: 'full_body',
        instructions: ['호흡을 가다듬습니다'],
        tips: [],
        commonMistakes: [],
        caloriesPerMinute: 1,
      },
    }),
    prisma.exercise.upsert({
      where: { id: 'exercise-9' },
      update: {},
      create: {
        id: 'exercise-9',
        workoutId: 'workout-hiit-1',
        sortOrder: 9,
        name: '마운틴 클라이머',
        description: '코어와 심폐 지구력을 동시에 강화합니다.',
        videoUrl: '/exercises/mountain-climber.mp4',
        thumbnailUrl: '/exercises/mountain-climber.jpg',
        type: 'timed',
        duration: 45,
        sets: 1,
        primaryMuscle: 'core',
        secondaryMuscles: ['legs', 'arms'],
        instructions: [
          '플랭크 자세에서 시작합니다',
          '오른쪽 무릎을 가슴 쪽으로 당깁니다',
          '빠르게 다리를 교체합니다',
          '달리듯이 반복합니다',
        ],
        tips: ['엉덩이를 낮게 유지합니다', '코어에 힘을 유지합니다'],
        commonMistakes: ['엉덩이가 올라가는 것', '동작이 너무 느린 것'],
        modifications: {
          easier: '천천히 수행',
          harder: '크로스 바디 마운틴 클라이머',
        },
        caloriesPerMinute: 12,
      },
    }),
    prisma.exercise.upsert({
      where: { id: 'exercise-10' },
      update: {},
      create: {
        id: 'exercise-10',
        workoutId: 'workout-hiit-1',
        sortOrder: 10,
        name: '휴식',
        description: '다음 동작을 위한 짧은 휴식입니다.',
        videoUrl: '/exercises/rest.mp4',
        thumbnailUrl: '/exercises/rest.jpg',
        type: 'rest',
        duration: 15,
        sets: 1,
        primaryMuscle: 'full_body',
        instructions: ['호흡을 가다듬습니다'],
        tips: [],
        commonMistakes: [],
        caloriesPerMinute: 1,
      },
    }),
    prisma.exercise.upsert({
      where: { id: 'exercise-11' },
      update: {},
      create: {
        id: 'exercise-11',
        workoutId: 'workout-hiit-1',
        sortOrder: 11,
        name: '플랭크',
        description: '코어 안정성을 기르는 정적 운동입니다.',
        videoUrl: '/exercises/plank.mp4',
        thumbnailUrl: '/exercises/plank.jpg',
        type: 'timed',
        duration: 45,
        sets: 1,
        primaryMuscle: 'core',
        secondaryMuscles: ['arms', 'shoulders'],
        instructions: [
          '팔꿈치를 바닥에 대고 엎드립니다',
          '발끝으로 몸을 지지합니다',
          '몸을 일직선으로 유지합니다',
          '호흡을 유지하며 버팁니다',
        ],
        tips: ['배꼽을 척추 쪽으로 당깁니다', '시선은 바닥을 향합니다'],
        commonMistakes: ['엉덩이가 올라가거나 처지는 것', '호흡을 참는 것'],
        modifications: {
          easier: '무릎 대고 플랭크',
          harder: '사이드 플랭크',
        },
        caloriesPerMinute: 5,
      },
    }),
    prisma.exercise.upsert({
      where: { id: 'exercise-12' },
      update: {},
      create: {
        id: 'exercise-12',
        workoutId: 'workout-hiit-1',
        sortOrder: 12,
        name: '쿨다운 스트레칭',
        description: '운동을 마무리하는 스트레칭입니다.',
        videoUrl: '/exercises/cooldown.mp4',
        thumbnailUrl: '/exercises/cooldown.jpg',
        type: 'timed',
        duration: 120,
        sets: 1,
        primaryMuscle: 'full_body',
        instructions: [
          '천천히 호흡하며 근육을 이완합니다',
          '각 스트레칭을 20-30초 유지합니다',
          '무리하지 않습니다',
        ],
        tips: ['통증이 느껴지면 멈춥니다', '호흡을 깊게 합니다'],
        commonMistakes: ['스트레칭을 건너뛰는 것', '너무 빠르게 하는 것'],
        caloriesPerMinute: 2,
      },
    }),
  ]);

  console.log(`✅ Created ${exercises.length} exercises`);

  // Create virtual events
  const events = await Promise.all([
    prisma.virtualEvent.upsert({
      where: { id: 'event-1' },
      update: {},
      create: {
        id: 'event-1',
        name: '12월 30일 운동 챌린지',
        description: '12월 한 달간 30일 운동을 완료하고 특별한 메달을 획득하세요!',
        coverImageUrl: '/events/december-challenge.jpg',
        startDate: new Date('2024-12-01'),
        endDate: new Date('2024-12-31'),
        type: 'workout',
        goal: {
          type: 'workouts',
          bronze: 15,
          silver: 22,
          gold: 30,
          platinum: 30,
        },
        participantCount: 1234,
        rewards: [
          { tier: 'bronze', xp: 300, prize: '브론즈 메달' },
          { tier: 'silver', xp: 500, prize: '실버 메달' },
          { tier: 'gold', xp: 1000, prize: '골드 메달' },
          { tier: 'platinum', xp: 1500, prize: '플래티넘 메달 + 프리미엄 1주' },
        ],
        sponsors: [
          { name: 'FitQuest', logoUrl: '/sponsors/fitquest.png' },
        ],
      },
    }),
    prisma.virtualEvent.upsert({
      where: { id: 'event-2' },
      update: {},
      create: {
        id: 'event-2',
        name: '새해 새출발 100km 러닝',
        description: '1월에 총 100km를 달리고 새해를 건강하게 시작하세요!',
        coverImageUrl: '/events/new-year-running.jpg',
        startDate: new Date('2025-01-01'),
        endDate: new Date('2025-01-31'),
        type: 'running',
        goal: {
          type: 'distance',
          bronze: 30,
          silver: 60,
          gold: 100,
          platinum: 150,
        },
        registrationFee: 5000,
        participantCount: 856,
        rewards: [
          { tier: 'bronze', xp: 200, prize: '완주 메달' },
          { tier: 'silver', xp: 400, prize: '실버 메달' },
          { tier: 'gold', xp: 800, prize: '골드 메달' },
          { tier: 'platinum', xp: 1200, prize: '플래티넘 메달 + 러닝 기어' },
        ],
      },
    }),
  ]);

  console.log(`✅ Created ${events.length} virtual events`);

  // Create challenges
  const challenges = await Promise.all([
    prisma.challenge.upsert({
      where: { id: 'challenge-1' },
      update: {},
      create: {
        id: 'challenge-1',
        name: '일주일 플랭크 챌린지',
        description: '매일 플랭크 시간을 늘려가며 코어를 강화하세요!',
        coverImageUrl: '/challenges/plank-challenge.jpg',
        type: 'solo',
        category: 'strength',
        startDate: new Date(),
        endDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
        duration: 7,
        goal: {
          type: 'minutes',
          target: 21,
        },
        currentParticipants: 542,
        isPublic: true,
        rewards: {
          xp: 200,
          badge: 'plank_master',
          title: '플랭크 마스터',
        },
        createdById: 'system',
      },
    }),
  ]);

  console.log(`✅ Created ${challenges.length} challenges`);

  console.log('🎉 Database seed completed!');
}

main()
  .catch((e) => {
    console.error('❌ Seed failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
