apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: fitquest-api-pdb
  namespace: fitquest
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: fitquest
      app.kubernetes.io/component: api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: fitquest-web-pdb
  namespace: fitquest
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: fitquest
      app.kubernetes.io/component: web
